apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-data-provider
spec:
  selector:
    matchLabels:
      app: email-data-provider
  template:
    metadata:
      labels:
        app: email-data-provider
    spec:
      containers:
      - name: email-data-provider
        image: email-data-provider
        resources:
          limits:
            memory: "300Mi"
            cpu: "200m"
        ports:
        - containerPort: 8585
        env:
        - name: CONFIG_SERVER_HOST
          valueFrom: 
            configMapKeyRef:
              name: pm-config-map
              key: configServerHost
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongoPassword
              name: pm-secret
          
---
apiVersion: v1
kind: Service
metadata:
  name: email-data-provider
spec:
  selector:
    app: email-data-provider
  ports:
  - port: 8585
    targetPort: 8585
                    
