apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway
        resources:
          limits:
            memory: "300Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_SERVER_HOST
          valueFrom: 
            configMapKeyRef:
              name: pm-config-map
              key: configServerHost
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer  
              
